In [2]:
import numpy as np

In [43]:
a = [
    [-4, 1, 0, 1, 0, 0, 0, 0],
    [1, -4, 1, 0, 0, 0, 0, 0],
    [0, 1, -4, 0, 1, 0, 0, 0],
    [1, 0, 0, -4, 0, 1, 0, 0],
    [0, 0, 1, 0, -4, 0, 0, 1],
    [0, 0, 0, 1, 0, -4, 1, 0],
    [0, 0, 0, 0, 0, 1, -4, 1],
    [0, 0, 0, 0, 1, 0, 1, -4],
    [0, 1, 0, 1, 1, 0, 1, 0]
    ]

b = [0, 1, 0, 1, 1, 0, 1, 0, -1]

a = np.array(a)
b = 4*np.array(b)

In [44]:
a_inv = np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

In [29]:
a_inv

array([[-0.28869048, -0.07738095, -0.02083333, -0.07738095, -0.00595238,
        -0.02083333, -0.00595238, -0.00297619],
       [-0.07738095, -0.28869048, -0.07738095, -0.02083333, -0.02083333,
        -0.00595238, -0.00297619, -0.00595238],
       [-0.02083333, -0.07738095, -0.28869048, -0.00595238, -0.07738095,
        -0.00297619, -0.00595238, -0.02083333],
       [-0.07738095, -0.02083333, -0.00595238, -0.28869048, -0.00297619,
        -0.07738095, -0.02083333, -0.00595238],
       [-0.00595238, -0.02083333, -0.07738095, -0.00297619, -0.28869048,
        -0.00595238, -0.02083333, -0.07738095],
       [-0.02083333, -0.00595238, -0.00297619, -0.07738095, -0.00595238,
        -0.28869048, -0.07738095, -0.02083333],
       [-0.00595238, -0.00297619, -0.00595238, -0.02083333, -0.02083333,
        -0.07738095, -0.28869048, -0.07738095],
       [-0.00297619, -0.00595238, -0.02083333, -0.00595238, -0.07738095,
        -0.02083333, -0.07738095, -0.28869048]])

In [30]:
x = np.matmul(a_inv, -np.vstack(b))
x

array([[0.66666667],
       [1.33333333],
       [0.66666667],
       [1.33333333],
       [1.33333333],
       [0.66666667],
       [1.33333333],
       [0.66666667]])

In [41]:
(np.matmul(a, x) + b)

array([[ 0.0000000e+00,  4.0000000e+00,  0.0000000e+00,  4.0000000e+00,
         4.0000000e+00,  0.0000000e+00,  4.0000000e+00,  0.0000000e+00],
       [-4.0000000e+00,  4.4408921e-16, -4.0000000e+00,  4.4408921e-16,
         4.4408921e-16, -4.0000000e+00,  4.4408921e-16, -4.0000000e+00],
       [ 0.0000000e+00,  4.0000000e+00,  0.0000000e+00,  4.0000000e+00,
         4.0000000e+00,  0.0000000e+00,  4.0000000e+00,  0.0000000e+00],
       [-4.0000000e+00,  8.8817842e-16, -4.0000000e+00,  8.8817842e-16,
         8.8817842e-16, -4.0000000e+00,  8.8817842e-16, -4.0000000e+00],
       [-4.0000000e+00,  8.8817842e-16, -4.0000000e+00,  8.8817842e-16,
         8.8817842e-16, -4.0000000e+00,  8.8817842e-16, -4.0000000e+00],
       [ 0.0000000e+00,  4.0000000e+00,  0.0000000e+00,  4.0000000e+00,
         4.0000000e+00,  0.0000000e+00,  4.0000000e+00,  0.0000000e+00],
       [-4.0000000e+00, -8.8817842e-16, -4.0000000e+00, -8.8817842e-16,
        -8.8817842e-16, -4.0000000e+00, -8.8817842e-16, -4

In [42]:
(a_inv @ a) 

array([[ 1.00000000e+00, -1.38777878e-17, -6.07153217e-18,
        -1.38777878e-17,  8.67361738e-19, -6.93889390e-18,
         4.33680869e-18, -3.46944695e-18],
       [-1.38777878e-17,  1.00000000e+00, -1.38777878e-17,
        -6.07153217e-18, -5.20417043e-18,  4.33680869e-19,
         8.67361738e-19, -3.46944695e-18],
       [-6.07153217e-18,  0.00000000e+00,  1.00000000e+00,
         4.33680869e-19, -1.38777878e-17,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -6.07153217e-18,  4.33680869e-19,
         1.00000000e+00,  0.00000000e+00, -1.73472348e-17,
         7.80625564e-18, -3.46944695e-18],
       [-4.33680869e-19,  1.38777878e-17,  0.00000000e+00,
         1.73472348e-18,  1.00000000e+00,  0.00000000e+00,
         1.38777878e-17,  0.00000000e+00],
       [ 1.38777878e-17, -3.90312782e-18,  3.46944695e-18,
         0.00000000e+00, -3.46944695e-18,  1.00000000e+00,
         3.81639165e-17,  0.00000000e+00],
       [-3.46944695e-18, -8.673617